name: CI
on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --no-root
    - name: Run pre-commit
      run: |
        poetry run pre-commit run --hook-stage push
    - name: Run mypy
      run: |
        poetry run mypy --ignore-missing-imports helium.py ./lib/*.py

  test_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x32, x64]
    container: sublimetext/unittesting:${{ matrix.arch }}
    env:
      SUBLIME_TEXT_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - run: sh -e /etc/init.d/xvfb start
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh sbin/github.sh bootstrap
          sh sbin/github.sh install_color_scheme_unit
          sh sbin/github.sh install_package_control
          sh sbin/github.sh run_tests --coverage
      - run: |
          apt-get update
          apt-get install python3-pip -y
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          export PATH="$HOME/.local/bin:$PATH"
          sh sbin/github.sh bootstrap
          sh sbin/github.sh install_color_scheme_unit
          sh sbin/github.sh install_package_control
          sh sbin/github.sh run_tests --coverage
      - run: |
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  test_windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x32, x64]
    env:
      SUBLIME_TEXT_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          ./sbin/github.ps1 "bootstrap" -verbose
          ./sbin/github.ps1 "install_color_scheme_unit" -verbose
          ./sbin/github.ps1 "install_package_control" -verbose
          ./sbin/github.ps1 "run_tests" -coverage -verbose
      - run: |
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
